{{- /*
ServiceAccount template for MEGA LOG
*/ -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "megalog.serviceAccountName" . }}
  labels:
    {{- include "megalog.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "megalog.fullname" . }}
  labels:
    {{- include "megalog.labels" . | nindent 4 }}
rules:
{{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "megalog.fullname" . }}
  labels:
    {{- include "megalog.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "megalog.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "megalog.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
